export {
  AUDIO_ACCEPT,
  getImageFiles,
  getMaxSizeForKind,
  getUploadKind,
  IMAGE_ACCEPT,
  isAudioFile,
  isImageFile,
  isVideoFile,
  MAX_AUDIO_SIZE,
  MAX_FILE_SIZE,
  MAX_IMAGE_SIZE,
  MAX_VIDEO_SIZE,
  VIDEO_ACCEPT,
} from './media-upload-shared'
